name: Build and Test
on:
  push:
    branches:
      - master
    tags:
      - v*
jobs:
  pytest:
    name: Run Pytest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
        tf-version: [2.4, 2.5, 2.7]
        exclude:
          - python-version: 3.9
            tf-version: 2.4
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache Env
        uses: actions/cache@v2
        with:
          path: ./.venv
          key: ${{ runner.os }}-venv-py${{ matrix.python-version }}-tf${{ matrix.tf-version }}--${{ hashFiles('./requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv-py${{ matrix.python-version }}-tf${{ matrix.tf-version }}--${{ hashFiles('./requirements*.txt') }}
            ${{ runner.os }}-venv-py${{ matrix.python-version }}-tf${{ matrix.tf-version }}
      - name: Install dependencies
        if: steps.cache-venv.outputs.cache-hit != 'true'
        run: |
          python3 -m venv ./.venv
          . ./.venv/bin/activate
          pip install tensorflow==${{ matrix.tf-version }}
          pip install -r requirements-dev.txt
          pip install -r requirements-doc.txt
      - name: Install PiNN
        run: |
          . ./.venv/bin/activate
          pip install .
      - name: Test with pytest
        run: |
          . ./.venv/bin/activate
          pytest --forked tests/
  build:
    name: Build docker (cpu)
    needs: pytest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Get Tag
        run: echo "TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_REPO }}:${{ env.TAG }}-cpu
  build-gpu:
    name: Build docker (gpu)
    needs: pytest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Get Tag
        run: echo "TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          file: Dockerfile.gpu
          tags: ${{ secrets.DOCKERHUB_REPO }}:${{ env.TAG }}-gpu
  deploy-docs:
    name: Deploy docs
    needs: pytest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # see https://github.com/jimporter/mike/issues/28
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Cache Env
        uses: actions/cache@v2
        with:
          path: ./.venv
          key: ${{ runner.os }}-venv-py3.9-tf2.5--${{ hashFiles('./requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv-py3.9-tf2.5--${{ hashFiles('./requirements*.txt') }}
            ${{ runner.os }}-
      - name: Install PiNN
        run: |
          . ./.venv/bin/activate
          pip install .
      - name: Configure Git user
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      - name: Deploy docs
        run: |
          . ./.venv/bin/activate
          mike deploy ${GITHUB_REF##*/} -b gh-pages -p
